project_id = "ivasmxvigcojbefxbzfk"

[functions.run-daily-digest]
verify_jwt = true

[functions.settings-save]
verify_jwt = true

[functions.task-operations]
verify_jwt = true

[functions.initial-fetch]
verify_jwt = true

[functions.chat-assistant]
verify_jwt = true